const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const nav=document.querySelector('#nav'); const menu=document.querySelector('#menu');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');menu.setAttribute('aria-expanded',String(open));});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('is-open');menu?.setAttribute('aria-expanded','false');}));
if(!reduced&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));}else document.querySelectorAll('[data-reveal]').forEach(el=>el.classList.add('is-visible'));
const stays={house:'Вы смотрите пространство дома.',water:'Вы выбрали воду: каяк, залив и открытый горизонт.',fire:'Вы выбрали огонь: вечер без расписания.'};
document.querySelectorAll('.stay-item').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.stay-item').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelector('#stay-status').textContent=stays[button.dataset.stay];}));
const form=document.querySelector('#contact-form'); const status=document.querySelector('#form-status');
form?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);const name=String(data.get('name')||'').trim();const email=String(data.get('email')||'').trim();if(name.length<2||!email.includes('@')){status.textContent='Проверьте имя и email.';status.className='form-status error';return;}const id=`NC-${Date.now().toString().slice(-6)}`;localStorage.setItem('nocta-demo-request',JSON.stringify({id,name,email}));status.textContent=`Спасибо, ${name}. Запрос ${id} сохранён в демо-контуре.`;status.className='form-status ok';form.reset();});
